#!/bin/bash

# Script to automate the process of extraction and compression of files
# Version: 0.2

help_() {
    echo -e "Usage: eac [option] foo
Options:
-c\tCompress
-e\tExtract"
}

while getopts ":c:C:e:E:" option
do
    case ${option} in
        c|C)
            if [ -f $2 ]; then
                tar cvzf "${2%%/}.tar.gz" "${2%%/}/"
                echo "$2.tar.gz created."
            else
                echo "File $2 not found!"
            fi
            ;;
        e|E)
            if [ -f $2 ]; then
                case $2 in
                    *.tar.gz)   tar xzvf $2 ;;
                    *.tar.bz2)  tar xvjf $2 ;;
                    *.tar.xz)   tar xvJf $2 ;;
                    *.tar)      tar xvf $2 ;;
                    *.zip)      unzip $2 ;;
                    *.rar)      unrar x $2 ;;
                    *.7z)       7z x $2 ;;
                    *.gz)       gzip -dk $2 ;;
                    *.xz)       xz -dk $2 ;;
                    ?*)         echo "Not able to extract $2!" ;;
                esac
            else
                echo "$2 is not valid file!"
            fi
            ;;
        ?*)
            help_ ;;
    esac
done
