#!/bin/bash

# set of commands to setup git, nothing special yet

# need to provide username and e-mail otherwise current user name will be set
_username="$LOGNAME"
_mail=""
_edit="vim"

sudo apt update
sudo apt install -y git

# Set git to use credential memory cache
git config --global credential.helper cache

# Set cache timeout at 10 hours (time is in seconds)
git config --global credential.helper 'cache --timeout=36000'

# Set username
git config --global user.name "${_username}"

# Set email
git config --global user.email "${_mail}"

# Editor
git config --global core.editor "${_edit}"

# Aliases
git config --global alias.ph push
git config --global alias.co checkout
git config --global alias.st status
git config --global alias.a add
git config --global alias.co commit
git config --global alias.alias --get-regexp alias
