#!/bin/bash

# set of commands to setup git nothing special yet

#need to provide username and e-mail
_mail=""
_username=""

sudo -v || echo "User need root privileges."

sudo apt update
sudo apt install -y git

# Set git to use credential memory cache
git config --global credential.helper cache

# Set cache timeout at 10 hours (time is in seconds)
git config --global credential.helper 'cache --timeout=36000'

# Set username
git config --global user.name "_username"

# Aliases
git config --global alias.ph push
git config --global alias.co checkout
git config --global alias.st status
git config --global alias.a add
git config --global alias.mm commit
