#!/bin/bash

# Script to semi automate system update on Debian based distros
# Version: 0.3

sources() {
    clear
    ls /etc/apt/sources.list.d

    echo -en "\nEnter file name to edit. If none selected sources.list will be edited.\nFile name: "
    read filename

    # edit-sources using default system editor
    sudo apt edit-sources $filename
}

help_() {
    clear
    echo -e "Description:\nA script to semi automate the update procedure on Debian based distributions."
    echo
    echo -e "Usage:\nSelect an option from the menu provided. Both lower and capital letters work."
    echo
    echo "$menu"
    read -p "Press Enter to continue"
}

_LESS=$(which less)

menu="1 - Update
2 - Upgrade
3 - Dist-Upgrade
L - List Available Upgrades
A - apt Autoremove
O - Remove Obsolete Packages
D - Purge Packages using deborphan
C - apt Clean
V - apt history log
E - Edit source.list files
H - Info and help
Q - Exit"

while true; do
    clear
    echo "$menu"
    echo -n "Enter option: "
    read option
    case $option in
        1) sudo apt update ;;
        2) sudo apt upgrade -V ;;
        3) sudo apt dist-upgrade ;;
        l|L) apt list --upgradable 
            read -p "Press Enter to continue" ;;
        a|A) sudo apt autoremove --purge ;;
        o|O) sudo aptitude purge ~o ;;
        d|D) sudo apt purge $(deborphan) ;; #deborphan package must be installed
        c|C) sudo apt clean ;;
        v|V) ${_LESS} /var/log/apt/history.log ;;
        e|E) sources ;;
        h|H) help_ ;;
        q|Q) exit 0 ;;
        ?*) echo "Error: $option option is not valid. Try again.."
            sleep 2 ;;
    esac
done
