#!/bin/bash

# A script to semi automate the packages update procedure and cleanup on Debian based
# distributions using the apt package manager and other packages.
# Version: 0.5

sudo_check_() {
    sudo -v || exit 1
}

sources_() {
    clear
    ls -l /etc/apt/sources.list.d/ | awk '{print $9}'

    echo -en "\nEnter file name to edit. If none selected sources.list will be edited.\nFile name: "
    read filename

    # edit-sources using default system editor
    sudo apt edit-sources $filename
    sudo apt update
}

pkgs_check_() {
    for pkg in "${_PKG[@]}"; do
        if [ -z $(which $pkg) ]; then
            echo -e "INFO: $pkg package is not installed."
        fi
    done
}

help_() {
    # launch default browser to view help file on github
    echo "VERSION: ${_VERSION}"
    sensible-browser https://github.com/sianios/dotfiles/blob/master/update.md &

    read -p "Press Enter to continue"
}

MENU="1 - Update
2 - Upgrade
3 - Full-Upgrade
L - List Available Upgrades
A - Autoremove
O - Remove Obsolete Packages
D - Purge Packages using deborphan
C - apt Clean
V - apt history log
E - Edit source.list files
H - Info and help
Q - Exit"

_VERSION="0.5"
_PKG=(sudo aptitude deborphan less)
_LESS=$(which less)

sudo_check_
pkgs_check_

while true; do
    clear
    echo -e "${MENU}"
    echo -n "Enter option: "
    read option
    case $option in
        1) sudo apt update ;;
        2) sudo apt upgrade -V ;;
        3) sudo apt full-upgrade ;;
        l|L) apt list --upgradable 
            read -p "Press Enter to continue" ;;
        a|A) sudo apt autoremove --purge ;;
        o|O) sudo aptitude purge ~o ;;
        d|D) sudo apt purge $(deborphan) ;;
        c|C) sudo apt clean ;; # Clean localy downloaded packages
        v|V) ${_LESS} /var/log/apt/history.log ;;
        e|E) sources_ ;;
        h|H) help_ ;;
        q|Q) exit 0 ;;
        ?*) echo "Error: $option option is not valid. Try again.."
            sleep 2 ;;
    esac
done
